language: erlang
script: "make all"
notifications:
  irc: "irc.freenode.org#turnusol"
  recipients:
    - mahmutbulut@icloud.com
otp_release:
    - R16B02
    - R16B01
    - R15B03
    - R15B02
    - R15B01
    - R14B04
    - R14B03
    - R14B02
